name: CI Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # Change to 'windows-latest' for Windows-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [[ "$(uname)" == "Linux" ]]; then
            python -m pip install --only-binary=pandas -r requirements.txt
          else
            python -m pip install -r requirements.txt
          fi

      - name: Run tests
        run: |
          pytest
