name: CI Pipeline

on:
  # Commenting out the push event will stop automatic triggers
  # push:
  #   branches:
  #     - master
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest  # or 'windows-latest' for Windows-based runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Cache pip dependencies for faster builds (optional)
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Install pytest  # Install pytest explicitly
        run: |
          python -m pip install pytest

      - name: List files  # Debug step to list files in the current directory
        run: |
          ls -la

      - name: Run tests
        run: |
          pytest
